### ISSUE TITLE
No need for double precision in ranks

### ISSUE THREAD

**Issue by osorensen** [ocbe-uio/BayesMallows#247]
Particularly in the original BayesMallows part we are using `arma::vec`, `arma::mat` etc to keep the ranks. This is unnecessary, and also leads to some unnecessary conversion issues. I guess `arma::uvec` and `arma::umat` could be the best alternative, since the ranks are constrained to be positive integers.

**Comment by wleoncio** [comment]
There's lots of that in the SMC functions too, BTW.

**Comment by wleoncio** [comment]
Hi @osorensen,

I started working on this issue, and I'd like your help working out the kinks. To summarize:

1. I started changing `rankings` form `mat` to `umat`. As expected, this led me down a rabbit hole that only ended after I made all the changes shown in commit 1178eb5 (see diff on the link).
2. What I wasn't expecting was that all NAs would be converted to zeros. The [Armadillo docs](https://arma.sourceforge.net/docs.html#Mat) explain that matrix types with integer elements cannot contain Inf and NA. The workaround I found for this was to replace `find_nonfinite(x)` with `find( x == 0)`, which is what I did on commit cf5aa6e, but I'm quite worried about other implications of this NA-to-zero conversion I missed. Can you think of any other place that could have been affected?
3. The package compiles fine, but the unit tests are failing. Most of the failures seem minor and could be due to RNG differences (which I find odd, since changes in variable types shouldn't move the RNG sequence, but OK), so I started adjusting the test expectations until I came across this:

![bilde](https://github.com/ocbe-uio/BayesMallows/assets/8234768/f974ed31-cbdb-4996-82f8-092f63a59170)

And that made me suspect somehting wrong is going on `compute_mallows()`, unless those distances can really take such large numbers. Maybe some of the distance functions on distances.cpp should be kept as doubles (which causes compilation errors unless we convert the objects when calling the function)?

These changes are available on the `issue-247` branch so you can take a look on your machine if you like. I also had a quick chat with Valeria because I was worried about rankings receiving zero or non-integer values, but I understood that shouldn't happen anyway, so maybe it's not so bad that we treat zeros as NA (on the rankings; maybe on other objects it could be a problem)?

Looking forward to your feedback. I gotta take a break from this after two days banging my head. 🤕

**Comment by osorensen** [comment]
Thanks for all your efforts, and for the detailed explanations of what happens! I'll take a closer look at this next week and get back to you then.

The screenshot from the tests that you attached made me think of overflow issues. C++ `int`s go up to 2147483647, and I guess `uint` goes to twice that. We can definitely get distances and other values (particularly normalizing constants) in intermediate computations that go higher than that.

**Comment by wleoncio** [comment]
Just to record a note I have on my desk, here's a list of keywords that indicate variables that may be integers:

- [ ] rank
- [ ] item
- [ ] rho? (not sure about this one: the code kind of requires it, but the paper seems to be fine working non-integers)
- [ ] loop counters
- [ ] freq
- [ ] cluster
- [ ] N

**Comment by osorensen** [comment]
Hi @wleoncio, I accidentally deleted the branch related to this issue, when I meant to delete the branch related to #299... Sorry about that! Hope you have it on your local machine...

**Comment by wleoncio** [comment]
No worries, I got a copy here. :)

**Comment by osorensen** [comment]
I've looked into it, and this isn't as easy as one would expect. There are lots of quantities in the package that need double precision, e.g., likelihood, acceptance ratios, partition functions, and in addition, we need to use functions like `std::pow` and `std::log` which work best with double precision numbers. Hence, using integers to represent ranks might introduce the need for conversions between types. I hence believe it's best to keep double precision for now.
