### ISSUE TITLE
metrics for estimate_partition_function

### ISSUE THREAD

**Issue by cmollica** [ocbe-uio/BayesMallows#45]
The documentation says that the available metrics are only "footrule" and "spearman", whereas the current 'estimate_partition_function' actually works with every metric. Could the implementation of 'estimate_partition_function' be limited to the only three metrics for which it is actually needed ("footrule", "spearman" and also "ulam", where the last one is not mentioned in the doc)? In any case, the doc should be modified accordingly.

**Comment by wleoncio** [comment]
Thank you for your contribution, @cmollica, this sounds like a proposal worth addressing.

Hey @osorensen, I've just enabled the [Discussions tab](https://github.com/ocbe-uio/BayesMallows/discussions) for this repository, maybe we can convert this issue into an Idea there. There's a "convert to discussion" button on the sidebar below, but I didn't press it because it's a destructive operation (the issue gets deleted in the conversion process, though its content should be completely transfered).

**Comment by osorensen** [comment]
Thank you, @cmollica . The reason why it says only "footrule" and "spearman" is that these are the only distances for which one can compute the asymptotic approximation based on Mukherjee's method. However, all metric can be used with importance sampling. I will update the function so that it specifies this properly.

**Comment by osorensen** [comment]
This issue is solved by #47 .
